version: '2'
services:
    liams-app:
        image: liams
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://liams-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=Liams
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=liams-elasticsearch:9300
        ports:
            - 8080:8080
    liams-mongodb:
        extends:
            file: mongodb.yml
            service: liams-mongodb
    liams-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: liams-elasticsearch
